name: Use Herald
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  herald:
    runs-on: ubuntu-latest

    steps:
      - name: Apply Herald Rules
        uses: gagoar/use-herald-action@master
        id: herald
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          rulesLocation: 'herald_rules/*.json'
          DEBUG: '*'
      - name: Store applied rules to file
        run: echo '${{ fromJSON(steps.herald.outputs.appliedRules) }}'

